targets:
    $default:
        builders:
            json_serializable:
                generate_for:
                    include:
                        - lib/app/domain/model/**/*
                        - lib/app/domain/model/*
            frezeed:
                generate_for:
                    include:
                        - lib/app/presentation/**/**_state.dart
                        - lib/app/model/**/*
                        - lib/app/domain/failures/**/*
                        - lib/app/domain/failures/http_request/*
                        - lib/app/domain/either/either.dart
