/// Flutter icons HouseCustom
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HouseCustom
///      fonts:
///       - asset: fonts/HouseCustom.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HouseCustom {
  HouseCustom._();

  static const _kFontFam = 'HouseCustom';
  static const String? _kFontPkg = null;

  static const IconData image2vector = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
